---
# tasks file for samba

- name: Include variable validation tasks
  ansible.builtin.include_tasks: assert.yml
  tags:
    - samba
    - validate

- name: Include Samba configuration tasks
  ansible.builtin.include_tasks: samba.yml
  tags:
    - samba
    - install
    - config
    - service
