---

- name: "Check if user {{ item.name }} already exists"
  ansible.builtin.command: "pdbedit -w -L {{ item.name }}"
  changed_when: false
  failed_when:
    - smb_cmd_result.rc not in [0, 255]
    - smb_cmd_result.rc == 0 and (smb_cmd_result.stdout is not regex('^.+?:.+?:.+?:.+:.+?:.+:'))
  register: smb_cmd_result

- name: "Create user {{ item.name }} if it does not exist"
  ansible.builtin.shell: |
    set -o pipefail
    (echo '{{ item.password }}'; echo '{{ item.password }}') |
    smbpasswd -s -a {{ item.name }}
  args:
    executable: /bin/bash
  changed_when: true
  when:
    - smb_cmd_result is defined
    - smb_cmd_result.rc == 255

- name: If user did exist, change password if needed
  vars:
    oldpwd: "{{ smb_cmd_result.stdout.split(':')[3] }}"
    newpwd: "{{ item.password | nt_hash | upper }}"
  ansible.builtin.shell: |
    set -o pipefail
    (echo '{{ item.password }}'; echo '{{ item.password }}') |
    smbpasswd -s -a {{ item.name }}
  args:
    executable: /bin/bash
  changed_when: true
  when:
    - smb_cmd_result is defined
    - smb_cmd_result.stdout is regex('^.+?:.+?:.+?:.+:.+?:.+:')
    - oldpwd != newpwd
