---
- name: Check whether Samba user exists
  ansible.builtin.command:
    argv:
      - pdbedit
      - -w
      - -L
      - "{{ item.name }}"
  register: smb_user_query
  changed_when: false
  failed_when:
    - smb_user_query.rc not in [0, 255]
    - smb_user_query.rc == 0 and (smb_user_query.stdout is not regex('^.+?:.+?:.+?:.+:.+?:.+:'))
  no_log: true
  tags:
    - samba
    - validate

- name: Create Samba user when absent
  ansible.builtin.shell: |
    set -o pipefail
    (printf '%s\n' '{{ item.password }}'; printf '%s\n' '{{ item.password }}') |
    smbpasswd -s -a '{{ item.name }}'
  args:
    executable: /bin/bash
  changed_when: true
  when:
    - smb_user_query is defined
    - smb_user_query.rc == 255
  no_log: true
  tags:
    - samba
    - config

- name: Update Samba user password when changed
  vars:
    smb_existing_password_hash: "{{ smb_user_query.stdout.split(':')[3] }}"
    smb_desired_password_hash: "{{ item.password | nt_hash | upper }}"
  ansible.builtin.shell: |
    set -o pipefail
    (printf '%s\n' '{{ item.password }}'; printf '%s\n' '{{ item.password }}') |
    smbpasswd -s -a '{{ item.name }}'
  args:
    executable: /bin/bash
  changed_when: smb_existing_password_hash != smb_desired_password_hash
  when:
    - smb_user_query is defined
    - smb_user_query.stdout is regex('^.+?:.+?:.+?:.+:.+?:.+:')
    - smb_existing_password_hash != smb_desired_password_hash
  no_log: true
  tags:
    - samba
    - config
